### ISSUE TITLE
What controller model this emulates?

### ISSUE THREAD

**Issue by tavasti** [philsuess/MackieEmulation#1]
I am using your code to investigate possibilities to emulate MCU with normal midi controller. What particular controller model your program emulates?

**Comment by philsuess** [comment]
This should be the standard Mackie protocol. There is some documentation online on it and also some other projects on github that use this protocol. See, for example: https://github.com/mzuther/PythonMcu

**Comment by tavasti** [comment]
Haven't found any too much documentation about MCP, and at least in Ardour there is several different controllers to select for MCP.

**Comment by philsuess** [comment]
Yes but they speak the same protocol.

**Comment by philsuess** [comment]
Some doc: http://www.emagic.de/media/support/content/manuals/LogicControl_en.pdf
